language: php
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
php:
  - 5.5

sudo: false

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"

  # Composer uses Bower to install our front-end dependencies.
  - npm install -g bower

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Let Composer do all the magic!
  - composer install

  # Install Lightning.
  - phing install -Ddb.database=drupal

before_script:
  - cd docroot
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - cd profiles/lightning
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - phpcs --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=*.css,*/karma.js,vendor,docroot,modules/contrib,bin,libraries $TRAVIS_BUILD_DIR
  - behat --strict
  - cd ./modules/lightning_features/lightning_media/tests/js
  # TODO: The install step should go into before_script.
  - npm install > /dev/null
  - npm test

matrix:
  fast_finish: true
